import hashlib
import hmac
import json
import re
import time
import urllib.parse
import uuid
from typing import Any, Optional

import httpx

BILIBILI_USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/131.0.0.0 Safari/537.36"
)

# Bilibili key parameters
APP_KEY = "1d8b6e7d45233436"
APP_SEC = "560c52ccd288fed045859ed18bffd973"
MIXIN_KEY_ENC_TAB = [
    46, 47, 18, 2, 53, 8, 23, 32, 15, 50, 10, 31, 58, 3, 45, 35,
    27, 43, 5, 49, 33, 9, 42, 19, 29, 28, 14, 39, 12, 38, 41, 13,
    37, 48, 7, 16, 24, 55, 40, 61, 26, 17, 0, 1, 60, 51, 30, 4,
    22, 25, 54, 21, 56, 59, 6, 63, 57, 62, 11, 36, 20, 52, 44, 34,
]


def _get_mixin_key(orig: str) -> str:
    return "".join(orig[i] for i in MIXIN_KEY_ENC_TAB)[:32]


def _sign_params(params: dict[str, Any]) -> dict[str, Any]:
    """Wbi sign the request parameters."""
    mixin_key = _get_mixin_key(_get_wbi_keys()["img_key"] + _get_wbi_keys()["sub_key"])
    params_sorted = dict(sorted(params.items()))
    params_sorted["wts"] = int(time.time())
    query = urllib.parse.urlencode(params_sorted)
    sign = hashlib.md5((query + mixin_key).encode()).hexdigest()
    params_sorted["w_rid"] = sign
    return params_sorted


# cached WBI keys
_wbi_cache: dict[str, Any] = {}
_wbi_cache_time = 0


def _get_wbi_keys() -> dict[str, str]:
    global _wbi_cache, _wbi_cache_time
    if _wbi_cache and time.time() - _wbi_cache_time < 3600:
        return _wbi_cache
    resp = httpx.get(
        "https://api.bilibili.com/x/web-interface/nav",
        headers={"User-Agent": BILIBILI_USER_AGENT},
    )
    data = resp.json()["data"]
    img_url = data["wbi_img"]["img_url"]
    sub_url = data["wbi_img"]["sub_url"]
    _wbi_cache = {
        "img_key": img_url.rsplit("/", 1)[-1].split(".")[0],
        "sub_key": sub_url.rsplit("/", 1)[-1].split(".")[0],
    }
    _wbi_cache_time = time.time()
    return _wbi_cache


class BilibiliSession:
    """Holds a Bilibili login session with cookies and tokens."""

    def __init__(self):
        self.cookies: dict[str, str] = {}
        self.client = httpx.AsyncClient(
            headers={
                "User-Agent": BILIBILI_USER_AGENT,
                "Referer": "https://www.bilibili.com/",
            },
            follow_redirects=True,
        )
        self.refresh_token: str = ""
        self.access_token: str = ""

    def absorb_response_cookies(self, resp: httpx.Response):
        """Extract all cookies from httpx response and merge into session."""
        for name, value in resp.cookies.items():
            if value:
                self.cookies[name] = value
        self.client.cookies.update(self.cookies)

    def set_cookies(self, raw: str | dict):
        """Parse Set-Cookie header string or dict into cookie jar."""
        if isinstance(raw, dict):
            self.cookies.update(raw)
        elif isinstance(raw, str):
            for item in raw.split(";"):
                item = item.strip()
                if "=" in item:
                    k, v = item.split("=", 1)
                    self.cookies[k.strip()] = v.strip()
        self.client.cookies.update(self.cookies)

    def get_cookie_string(self) -> str:
        return "; ".join(f"{k}={v}" for k, v in self.cookies.items())

    @property
    def sessdata(self) -> str:
        return self.cookies.get("SESSDATA", "")

    @property
    def bili_jct(self) -> str:
        return self.cookies.get("bili_jct", "")

    @property
    def dedeuserid(self) -> str:
        return self.cookies.get("DedeUserID", "")

    def dump_stored_values(self) -> dict[str, Any]:
        """Dump all known stored values from this session."""
        return {
            "cookies": dict(self.cookies),
            "sessdata": self.sessdata,
            "bili_jct": self.bili_jct,
            "dedeuserid": self.dedeuserid,
            "access_token": self.access_token,
            "refresh_token": self.refresh_token,
            "cookie_string": self.get_cookie_string(),
            # ac_time_value is derived from current time (Bilibili uses it as anti-replay)
            # It is normally generated by JS: Math.floor(Date.now() / 1000)
            "ac_time_value": int(time.time()),
            "ac_time_value_alt": str(int(time.time())),
        }


class BilibiliService:
    """Bilibili API service: QR login, user info, stored values."""

    def __init__(self):
        self._sessions: dict[str, BilibiliSession] = {}
        self._qrcode_store: dict[str, dict] = {}

    # ------------------------------------------------------------------ QR login

    async def get_login_url(self) -> dict:
        """Step 1: Get QR code login URL and key. Returns qrcode_key + url."""
        async with httpx.AsyncClient() as cli:
            resp = await cli.get(
                "https://passport.bilibili.com/x/passport-login/web/qrcode/generate",
                headers={"User-Agent": BILIBILI_USER_AGENT},
            )
        data = resp.json()
        if data["code"] != 0:
            raise RuntimeError(f"Bilibili QR generate failed: {data}")
        qr_data = data["data"]
        key = qr_data["qrcode_key"]
        qr_content = qr_data["url"]  # Bilibili returns QR code content URL, not an image
        self._qrcode_store[key] = {"status": "pending", "session": None}
        return {
            "qrcode_key": key,
            "url": qr_content,
            # Use qrserver API to generate an actual QR code image from the content
            "qrcode_image": f"https://api.qrserver.com/v1/create-qr-code/?size=200x200&data={urllib.parse.quote(qr_content, safe='')}",
        }

    async def poll_qr_login(self, qrcode_key: str) -> dict:
        """Step 2: Poll login status. Returns session_id on success."""
        async with httpx.AsyncClient() as cli:
            resp = await cli.get(
                "https://passport.bilibili.com/x/passport-login/web/qrcode/poll",
                params={"qrcode_key": qrcode_key},
                headers={"User-Agent": BILIBILI_USER_AGENT},
            )
        data = resp.json()
        code = data["code"]
        if code == 86101:
            return {"status": "waiting", "message": "等待扫码"}
        elif code == 86090:
            return {"status": "scanned", "message": "已扫码，等待确认"}
        elif code == 0:
            session = await self._build_session_from_qr(resp, data["data"])
            session_id = str(uuid.uuid4())[:8]
            self._sessions[session_id] = session
            self._qrcode_store[qrcode_key] = {"status": "done", "session_id": session_id}
            return {
                "status": "done",
                "session_id": session_id,
                "cookies": session.cookies,
                "refresh_token": session.refresh_token,
            }
        else:
            return {"status": "expired", "message": data.get("message", "二维码已过期")}

    async def _build_session_from_qr(self, response, login_data: dict) -> BilibiliSession:
        session = BilibiliSession()
        session.absorb_response_cookies(response)

        refresh_token = login_data.get("refresh_token", "")
        if refresh_token:
            session.refresh_token = refresh_token

        # Also extract tokens from login response body
        token = login_data.get("token", "")
        if token:
            session.access_token = token

        # Fetch fingerprint and nav info to warm up session
        await self._fetch_fingerprint(session)
        if session.sessdata:
            await self._fetch_nav_info(session)
        return session

    # ------------------------------------------------------------------ token exchange

    async def login_by_cookie(self, cookie_str: str) -> str:
        """Direct login with existing cookie string."""
        session = BilibiliSession()
        for item in cookie_str.replace(" ", "").split(";"):
            if "=" in item:
                k, v = item.split("=", 1)
                if k.strip():
                    session.cookies[k.strip()] = v.strip()
        session.client.cookies.update(session.cookies)

        await self._fetch_fingerprint(session)
        await self._fetch_nav_info(session)
        session_id = str(uuid.uuid4())[:8]
        self._sessions[session_id] = session
        return session_id

    # ------------------------------------------------------------------ user / nav info

    async def _fetch_nav_info(self, session: BilibiliSession) -> dict:
        resp = await session.client.get(
            "https://api.bilibili.com/x/web-interface/nav",
        )
        session.absorb_response_cookies(resp)
        return resp.json()

    async def get_nav_info(self, session_id: str) -> dict:
        session = self._sessions.get(session_id)
        if not session:
            raise KeyError(f"Session {session_id} not found")
        resp = await session.client.get(
            "https://api.bilibili.com/x/web-interface/nav",
            headers={"Referer": "https://www.bilibili.com/"},
        )
        session.absorb_response_cookies(resp)
        return resp.json()

    async def get_user_info(self, session_id: str) -> dict:
        session = self._sessions.get(session_id)
        if not session:
            raise KeyError(f"Session {session_id} not found")
        nav = await self.get_nav_info(session_id)
        return {
            "mid": nav.get("data", {}).get("mid"),
            "uname": nav.get("data", {}).get("uname"),
            "isLogin": nav.get("data", {}).get("isLogin"),
            "vip": nav.get("data", {}).get("vip"),
            "wallet": nav.get("data", {}).get("wallet"),
        }

    # ------------------------------------------------------------------ stored values

    async def get_all_stored_values(self, session_id: str) -> dict:
        """Retrieve all available stored values from the session."""
        session = self._sessions.get(session_id)
        if not session:
            raise KeyError(f"Session {session_id} not found")

        # Fetch nav info first to capture all cookies via Set-Cookie headers
        try:
            nav = await self.get_nav_info(session_id)
        except Exception:
            nav = None

        # Try to get additional tokens from Bilibili page
        try:
            page_tokens = await self._fetch_page_tokens(session)
        except Exception:
            page_tokens = None

        # Now dump everything including cookies collected above
        result = session.dump_stored_values()
        result["nav_info"] = nav.get("data") if nav else None
        result["page_tokens"] = page_tokens

        return result

    async def _fetch_fingerprint(self, session: BilibiliSession):
        """Fetch Bilibili device fingerprint (buvid3/buvid4 etc.) via spi endpoint."""
        # First, call the main spi endpoint to get buvid data
        headers = {
            "User-Agent": BILIBILI_USER_AGENT,
            "Referer": "https://www.bilibili.com/",
        }
        try:
            resp = await session.client.get(
                "https://api.bilibili.com/x/frontend/finger/spi",
                headers=headers,
            )
            session.absorb_response_cookies(resp)
            data = resp.json()
            if data.get("code") == 0 and data.get("data"):
                d = data["data"]
                # b_3 -> buvid3, b_4 -> buvid4
                if d.get("b_3"):
                    self._ensure_cookie(session, "buvid3", d["b_3"])
                if d.get("b_4"):
                    self._ensure_cookie(session, "buvid4", d["b_4"])
        except Exception:
            pass

        # Also try the gaia gateway (another fingerprint endpoint)
        try:
            resp = await session.client.get(
                "https://api.bilibili.com/x/internal/gaia-gateway/ExClimbWuzhi",
                headers=headers,
            )
            session.absorb_response_cookies(resp)
        except Exception:
            pass

        # Visit a common CDN endpoint that sets buvid cookies
        try:
            resp = await session.client.get(
                "https://api.bilibili.com/x/web-interface/online",
                headers=headers,
            )
            session.absorb_response_cookies(resp)
        except Exception:
            pass

    def _ensure_cookie(self, session: BilibiliSession, name: str, value: str):
        if value and name not in session.cookies:
            session.cookies[name] = value
            session.client.cookies.set(name, value, domain=".bilibili.com")

    async def _fetch_page_tokens(self, session: BilibiliSession) -> dict:
        """Fetch Bilibili main page and extract embedded tokens."""
        # Fetch fingerprints first
        await self._fetch_fingerprint(session)

        resp = await session.client.get(
            "https://www.bilibili.com/",
            headers={
                "User-Agent": BILIBILI_USER_AGENT,
                "Referer": "https://www.bilibili.com/",
            },
        )
        session.absorb_response_cookies(resp)
        html = resp.text

        tokens: dict[str, Optional[str]] = {}

        # Extract __RENDER_DATA__ (Bilibili's SSR data)
        m = re.search(r'window\.__RENDER_DATA__\s*=\s*({.*?})[\s;]', html)
        if m:
            try:
                tokens["__RENDER_DATA__"] = json.loads(m.group(1))
            except json.JSONDecodeError:
                tokens["__RENDER_DATA__"] = m.group(1)[:500]

        # Extract __INITIAL_STATE__
        m = re.search(r'window\.__INITIAL_STATE__\s*=\s*({.*?});', html)
        if m:
            try:
                tokens["__INITIAL_STATE__"] = json.loads(m.group(1))
            except json.JSONDecodeError:
                tokens["__INITIAL_STATE__"] = m.group(1)[:500]

        # Look for ac_time_value pattern
        m = re.search(r'ac_time_value[=:]\s*["\']?(\d+)["\']?', html)
        if m:
            tokens["ac_time_value_from_html"] = m.group(1)

        # Collect all fingerprint-related cookies
        fp_keys = ["buvid3", "buvid4", "buvid_fp", "b_nut", "_uuid", "b_lsid", "b_source", "sid"]
        for key in fp_keys:
            val = session.cookies.get(key)
            if val:
                tokens[key] = val

        # Timestamp values that Bilibili uses
        tokens["ac_time_value_current"] = int(time.time())
        tokens["ac_time_value_current_ms"] = int(time.time() * 1000)

        return tokens

    # ------------------------------------------------------------------ ac_time_value

    async def get_ac_time_value(self, session_id: str) -> dict:
        """Specifically try to retrieve ac_time_value."""
        session = self._sessions.get(session_id)
        if not session:
            raise KeyError(f"Session {session_id} not found")

        result: dict[str, Any] = {
            "timestamp": int(time.time()),
            "timestamp_ms": int(time.time() * 1000),
        }

        # ac_time_value is a client-side anti-replay value.
        # In Bilibili's current implementation, it's often:
        # 1. Encrypted/localStorage value set by their JS SDK
        # 2. Not accessible via server-side requests
        #
        # The value is typically used as `ac_time_value` header/param
        # and represents Math.floor(Date.now() / 1000) or
        # an encrypted timestamp.
        #
        # Since we can't execute JS, provide the timestamp and
        # try to fetch it from the Bilibili page itself.
        result["ac_time_value"] = int(time.time())

        try:
            resp = await session.client.get(
                "https://api.bilibili.com/x/web-interface/wbi/index/top/feed/0",
                headers={"Referer": "https://www.bilibili.com/"},
            )
            result["api_test"] = resp.status_code
        except Exception:
            result["api_test"] = "failed"

        return result

    # ------------------------------------------------------------------ check session

    def get_session(self, session_id: str) -> Optional[BilibiliSession]:
        return self._sessions.get(session_id)

    def list_sessions(self) -> list[str]:
        return list(self._sessions.keys())

    def delete_session(self, session_id: str):
        self._sessions.pop(session_id, None)
